### ISSUE TITLE
Implement prometheus based scraping

### ISSUE THREAD

**Issue by jonasz-lasut** [jonasz-lasut/configuration-ess-external-secrets#3]
Add new operator field:

```
operators:
  prometheus:
    enabled: true
    config: <type: object>
```
based on [Service Monitor values](https://artifacthub.io/packages/helm/external-secrets-operator/external-secrets?modal=values&path=serviceMonitor)
